name: taskwarrior
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_gen: ^5.4.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  file_selector: ^0.9.4
  file_picker_writable: ^2.1.0+1
  uuid: ^4.4.0
  flutter_local_notifications: ^17.1.2
  connectivity_plus: ^6.0.3
  loggy: ^2.0.3
  double_back_to_close_app: ^2.1.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  sizer: ^2.0.15
  flutter_slidable: ^3.1.0
  built_collection: ^5.1.1
  pem: ^2.0.5
  crypto: ^3.0.3
  tuple: ^2.0.2



dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/app/utils/gen/
  integrations:
    flutter_svg: true

flutter: 
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/SegoeUI.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900

