name: taskwarrior
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_gen: ^5.4.0
  flutter_svg: ^2.0.10+1

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/app/gen/
  integrations:
    flutter_svg: true

flutter: 
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/

